#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kcc
Version  : 0.0.8
Release  : 4
URL      : https://files.pythonhosted.org/packages/fa/44/949c55ccf7361230b198b6316714b8c9fb8d4ed3d00da793192f2ccb4809/kcc-0.0.8.tar.gz
Source0  : https://files.pythonhosted.org/packages/fa/44/949c55ccf7361230b198b6316714b8c9fb8d4ed3d00da793192f2ccb4809/kcc-0.0.8.tar.gz
Summary  : Check kernel config for security issues
Group    : Development/Tools
License  : GPL-3.0
Requires: kcc-bin = %{version}-%{release}
Requires: kcc-python = %{version}-%{release}
Requires: kcc-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Patch1: 0001-cli-Fix-query-option-3.patch
Patch2: 0002-defaults-Drop-STRICT-DEVMEM-requirement.patch

%description
===========================

%package bin
Summary: bin components for the kcc package.
Group: Binaries

%description bin
bin components for the kcc package.


%package python
Summary: python components for the kcc package.
Group: Default
Requires: kcc-python3 = %{version}-%{release}

%description python
python components for the kcc package.


%package python3
Summary: python3 components for the kcc package.
Group: Default
Requires: python3-core
Provides: pypi(kcc)

%description python3
python3 components for the kcc package.


%prep
%setup -q -n kcc-0.0.8
cd %{_builddir}/kcc-0.0.8
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1591911184
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/kcc

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
